### ISSUE TITLE
Stanford

### ISSUE THREAD

**Issue by jonahweissman** [jonahweissman/jonah-college#3]
### Why I'm applying
Good reputation, excellent computer science
### Tasks

- [x] SAT w/Essay
- [x] recommenders invited
- [x] Short Questions
  - [x] challenge for society
  - [x] last two summers
  - [x] historical moment
  - [x] five words to describe me
  - [ ] media choice
  - [x] experience at Stanford
  - [x] extra hour
- [x] supplemental essays
  - [x] extracurricular
  - [x] exciting idea
  - [ ] note to roommate
  - [x] something meaningful

**Comment by jonahweissman** [comment]
rejected

**Comment by freedomfry** [comment]
Lottery.
